# Generated by Django 2.0.7 on 2018-07-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ggituser',
            name='settings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
