# Generated by Django 2.0.7 on 2018-07-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteelement',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_elements', to='notes.Note'),
        ),
    ]
