# Generated by Django 2.0.7 on 2018-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
            preserve_default=False,
        ),
    ]
