# Generated by Django 2.0.7 on 2018-07-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_comment_note'),
        ('notes', '0003_auto_20180717_1750'),
    ]

    operations = [
    ]
