# Generated by Django 2.0.7 on 2018-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_merge_20180717_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
