# Generated by Django 2.0.7 on 2018-07-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_published'),
        ('notes', '0005_merge_20180717_2047'),
    ]

    operations = [
    ]
